### ISSUE TITLE
Error using the mask method

### ISSUE THREAD

**Issue by lebogan** [crystal-term/prompt#1]
My code:
```
require "term-prompt"
prompt = Term::Prompt.new
bullet = prompt.decorate(prompt.symbols[:bullet] + " ", :magenta)
res = prompt.mask("What is your secret? ", mask: bullet)
puts "Secret: \"#{res}\""
```
The error:
```
[term_stuff (master)]$ crystal run src/term_stuff.cr 
Showing last frame. Use --error-trace for full trace.

In lib/term-prompt/src/term-prompt.cr:114:16

 114 | question.call(message, &block)
                ^---
Error: expected block argument's argument #1 to be Term::Prompt::Question+, not Term::Prompt::MaskQuestion
```
What did I miss? Using Crystal 0.34.0.

PS- This is the type of terminal stuff I have been looking for. Big thumbs up!!!

**Comment by watzon** [comment]
Ahh man, I messed up. I'll fix it when I get home in a couple hours. Thanks for using this!

**Comment by watzon** [comment]
@lebogan try now. It should work.

**Comment by lebogan** [comment]
My shard.lock:
```
version: 1.0
shards:
  cor:
    github: watzon/cor
    commit: 4b6f8c210f7ae768ae283fc306967c66c7a8fae7

  term-cursor:
    github: crystal-term/cursor
    commit: 8805d5f686d153db92cf2ce3333433f8ed3708d0

  term-prompt:
    github: crystal-term/prompt
    commit: 8d5851293ec6baa755d71adb8dcc45c47ad55e98

  term-reader:
    github: crystal-term/reader
    commit: 3b29f462c62ad5c05c58778b5d7609ef7c9f42cb

  term-screen:
    github: crystal-term/screen
    commit: 96a06e1ee015e38013822dc31288a46d35056ed2

  term-spinner:
    github: crystal-term/spinner
    commit: 60350f9598335c559a8350d98fb2b9042e53290f
```
Am I using the correct commit?
